NUM_CLIENTS=100
NUM_EDGE_SERVERS=5
DURACION_SIMULACION=1000
ARRIVAL_TIME=1
WSECACHESIZE=8000
FLASHCROWD=1
TIME_WINDOW=10
CROWD_TIME=5
NORMAL_TIME=50
NORMAL_RATE=100
CROWDED_RATE=500
./main	$NUM_CLIENTS $NUM_EDGE_SERVERS $DURACION_SIMULACION $ARRIVAL_TIME $WSECACHESIZE $FLASHCROWD $TIME_WINDOW $CROWD_TIME $NORMAL_TIME $NORMAL_RATE $CROWDED_RATE